// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Token} from "../../src/Token.sol";

contract Tokenaccess_controlTest {
    function test_access_control_reproducible() public {
        // Deterministic proof scaffold generated by Raze.
        // Target function: mint
        Token target = new Token();
        require(address(target) != address(0), "target deployment failed");
    }
}
